version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "9292:9292"
    environment:
      - RACK_ENV=development
      - SESSION_TIMEOUT=3600
      - PRODUCT_CREATION_DELAY=5
      - DEFAULT_USERNAME=admin
      - DEFAULT_PASSWORD=password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9292/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    
  # Optional: Add nginx proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    profiles:
      - production
